### ISSUE TITLE
CancellationToken Support

### ISSUE THREAD

**Issue by matthawley** [microsoft/FeatureManagement-Dotnet#117] opened 2021-03-25 16:43 UTC
Curious if there's a reason why all the Async methods on IFeatureManager do not take a cancellation token? Can overloads be added that take this in and appropriately use them within the stack? If things aren't truly asynchronous, can synchronous methods be exposed?

**Comment by jimmyca15** [comment] 2021-03-25 16:59
@matthawley 

It's an oversight. Since IFeatureManager is an interface we need a breaking change release to address it. But it is known and we plan to address it when we have the opportunity to make a breaking change. Should be upcoming based off what we have in the works.

**Comment by zhiyuanliang-ms** [comment] 2023-09-08 08:28
Hi, @matthawley 
This issue will be solved in our next release.

**Comment by brental** [comment] 2024-03-11 01:32
@zhenlan @zhiyuanliang-ms In #376 we were discussing cancellation tokens and the fact that the FeatureManager class does not support them came up. I was going to raise a new issue for that to address it in v4 (as part of adding cancellation token support) but found this pre-existing issue. It would be good to ensure that support gets added as part of v4.

**Comment by zhiyuanliang-ms** [comment] 2024-03-11 05:39
@jimmyca15 @rossgrambo ISessionManager should take cancellation token too.

**Comment by brental** [comment] 2024-09-20 10:41
@zhenlan @zhiyuanliang-ms Are these changes still planned for v4.0.0? I ask because as per #500 the v4 code has been merged into main in prep for release but the changes to address this issue have not been implemented. It would be good to have these changes in as part of v4 given they would be breaking changes.

**Comment by jimmyca15** [comment] 2024-09-20 16:30
@brental v4 adds `IVariantFeatureManager` ([link](https://github.com/microsoft/FeatureManagement-Dotnet/blob/7050fa0c5138ad44860236f7496958b511ea8f6d/src/Microsoft.FeatureManagement/IVariantFeatureManager.cs#L38)). This interface is a superset of `IFeatureManager`, and it also supports cancellation token. 

Since this can be used for proper cancellation, we avoided any breaking change on `IFeatureManager`.

**Comment by jimmyca15** [comment] 2024-09-20 19:56
@brental

This issue should have been updated. The intention of the v4 release is to go without breaking changes. 

> Consumers should not be forced to use IVariantFeatureManager simply to have cancellation token support. So, I think the opportunity should be taken to make the breaking change so they also have proper cancellation token support.

I don't think it's so clear cut to say we should take a breaking change to modify `IFeatureManager` when `IVariantFeatureManager` will offer this functionality.

`ISessionManager` is another matter. Given we don't want to have breaking changes in v4, I might propose that we have a new interface that allows cancellation token.

**Comment by rossgrambo** [comment] 2024-09-23 16:47
Just wanted to note- `IVariantFeatureManager` can directly replace `IFeatureManager`. There is no change in functionality to the existing methods, like `IsEnabledAsync`. 

Another option is using `FeatureManager` directly to get the cancellation token methods. The direct class offers both methods with and without cancellation tokens in order to be backwards compatible, so I think `IVariantFeatureManager` is a better option.

**Comment by brental** [comment] 2024-09-23 18:08
I understand wanting to avoid breaking changes but it seems like that in this case that goal is going to result in the best abstractions to use becoming less obvious. If you were looking at the library you would probably think that IFeatureManager / IFeatureManagerSnapshot would be the primary abstractions to use to check features are enabled. However, from v4 those abstractions would not be the best way to check features are enabled given that the IVariantFeatureManager / IVariantFeatureManagerSnapshot abstractions support cancellation tokens and IFeatureManager / IFeatureManagerSnapshot don't. Introducing a new interface for cancellation token support for ISessionManager could result in a similar issue (depending on how it is named). It seems like that has been discussed though and was decided as preferable to making breaking changes so I will leave it there.

However, if the goal is to avoid breaking changes in v4 then I think there is a potential issue with change to make the FeatureManagerSnapshot class take IVariantFeatureManager instead of IFeatureManager in the constructor. If a consumer has registered a custom IFeatureManager implementation (but not a custom IFeatureManagerSnapshot implementation) then prior to v4 that would be used by FeatureManagerSnapshot. When they upgrade to v4, FeatureManagerSnapshot would revert to using FeatureManager as that would be the default registered IVariantFeatureNanager implementation (or throw an exception if there is no IVariantFeatureManager implementation registered). This would cause an unexpected behaviour change for those consumers. That is a separate issue to this one but needs some consideration as the consumer would have to make changes to maintain the same behaviour.

**Comment by jimmyca15** [comment] 2024-09-24 17:17
@brental

Thank you for raising this concern. This is an overlooked change that could introduce a difference in behavior.

**Comment by jimmyca15** [comment] 2024-09-24 17:17
@rossgrambo

**Comment by brental** [comment] 2024-11-03 09:29
@jimmyca15 Has there been any further discussion on cancellation token support in ISessionManager (or the new interface that supports cancellation tokens)?

**Comment by zhiyuanliang-ms** [comment] 2024-11-04 03:14
Hi, @brental The main reason why we don't add cancellation token to it now is that we want to avoid breaking changes. Do you have any specific scenario that eagerly requires `ISessionManager` to support cancellation token?

I don't think there is a way to avoid breaking change for this, unless we create a new interface called `ISessionManagerWithCancellationToken` but this looks ugly. If our decision is that finally we will support cancellation token for `ISessionManager`, then I think now is a good timing to take the breaking change. Otherwise, we have to wait for v5. What do you think? @rossgrambo @zhenlan  @jimmyca15 

BTW, we should give `ISessionManager` more love. At least document it. Track in #394

**Comment by rossgrambo** [comment] 2024-11-04 17:56
> BTW, we should give ISessionManager more love. At least document it. Track in https://github.com/microsoft/FeatureManagement-Dotnet/issues/394

Agreed.
 
I think we should go with `IVariantSessionManager`- since it also doesn't support variants yet. It will be a similar change to the `IFeatureManager` vs `IVariantFeatureManager` change. This means it's not breaking so we could add it in the next minor update.

**Comment by brental** [comment] 2024-12-13 09:04
@jimmyca15 @zhiyuanliang-ms @rossgrambo The session manager changes are being tracked in #394 and the other required cancellation token changes have been made. So, I think this issue could probably be closed now.

**Comment by zhiyuanliang-ms** [comment] 2024-12-16 02:41
@brental Thank you for pay attention to this!

**Closed by zhiyuanliang-ms** 2024-12-16 02:41 UTC
Labels: enhancement
