### ISSUE TITLE
IFeatureManager.GetFeatureNamesAsync returning all configuration keys

### ISSUE THREAD

**Issue by satuday** [microsoft/FeatureManagement-Dotnet#55] opened 2020-04-02 22:47 UTC
I dont have a 'FeatureManagement' section in my appsettings.json, but when I call GetFeatureNamesAsync, it is returning key in IConfiguration. 

I'd also try adding  'FeatureManagement' section without any feature set, but the result was the same.

the following are some of the names return from GetFeatureNamesAsync()

    "AllowedHosts"
    "ALLUSERSPROFILE"
    "APPDATA"
    "applicationName"
    "APP_POOL_CONFIG"
    "APP_POOL_ID"
    "ASPNETCORE_ENVIRONMENT"
    "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES"
    "ASPNETCORE_IIS_HTTPAUTH"
    "ASPNETCORE_IIS_PHYSICAL_PATH"

**Comment by jimmyca15** [comment] 2020-04-06 17:27
Hello @satuday,

When no FeatureManagement section is provided the library treats the root of the registered IConfiguration as the featuremanagement section. This is detailed [in the readme](https://github.com/microsoft/FeatureManagement-Dotnet#service-registration). 

Using a FeatureManagement section would be the proper method to prevent all configuration keys from being returned from this API. Otherwise, there is no way to distinguish a non-feature configuration key vs a feature configuration key.

**Comment by jimmyca15** [comment] 2020-04-16 17:17
Closing by design. To avoid this please use a "FeatureManagement" section in the application's configuration or pass in an IConfiguration instance which does not contain non-features.

**Closed by jimmyca15** 2020-04-16 17:17 UTC

**Comment by jgn-epp** [comment] 2022-01-25 14:20
Super confusing behavior IMO
