### ISSUE TITLE
Configure services depending on the enabled feature

### ISSUE THREAD

**Issue by VladimirLevchuk** [microsoft/FeatureManagement-Dotnet#35] opened 2019-12-12 14:10 UTC
Hi,

What's the correct way to checking whether feature enabled from Startup.ConfigureServices? 

I'd expect something like 
`
services.AddForFeature(MyFeatures.RedisCache, x => x.Decorate<IMyService, MyCachedService>());
`

or 
`if (configuration.IsFeatureEnabled(MyFeatures.RedisCache))
{
  services.Decorate<IMyService, MyCachedService>();
}`

but have not found a nice way of doing it. Have I missed something existing for this? Or such usage breaks design somehow?

**Comment by jimmyca15** [comment] 2019-12-19 19:16
It breaks the pattern a bit because that would be attempting to consume the feature manager before the service provider has been built. Right now there is no clean built-in way to do this, you would have to build an intermediate service provider which is not a good approach.

By the way, are you looking for something similar to what is discussed in this issue https://github.com/Azure/AppConfiguration/issues/68 ?

**Comment by VladimirLevchuk** [comment] 2020-04-13 15:57
Sorry for late response, correct, it's a duplicate of the existing  https://github.com/microsoft/FeatureManagement-Dotnet/issues/39

**Comment by qin-guan** [comment] 2020-10-12 07:48
hi, i have this code:

```csharp
        services.AddHttpClient("ApiServices",
                    c => { c.BaseAddress = new Uri(Urls.ApiUrl); })
                .ConfigurePrimaryHttpMessageHandler(() =>
                {
                    if (disableSslCertValidation)
                    {
                        return new HttpClientHandler
                        {
                            ServerCertificateCustomValidationCallback =
                                (message, certificate, chain, sslPolicyErrors) => true
                        };
                    }
                    return new HttpClientHandler();
                })
                .AddTypedClient(RestService.IFor<ApiServices>);
```

which would need to use feature management in `Startup.cs`, is there a way to do this? it seems similar to the issue @VladimirLevchuk mentioned

**Comment by rossgrambo** [comment] 2023-05-16 19:53
Closing as a duplicate of https://github.com/microsoft/FeatureManagement-Dotnet/issues/39

**Closed by rossgrambo** 2023-05-16 19:53 UTC
