### ISSUE TITLE
Targeting filter - Feature does not display even if setting the value to 100

### ISSUE THREAD

**Issue by brenda-campbell** [microsoft/FeatureManagement-Dotnet#371] opened 2024-02-21 16:32 UTC
Testing the functionality of feature filters - Time window filter works as expected. If using targeting filter, the feature does not appear to work as expected. Tried setting the value to 10, 50, 99 and 100 but page does not appear (no matter how many time I refresh). Removed the feature filter and page works as expected. Are there any known issues with this piece of functionality?

**Comment by jimmyca15** [comment] 2024-02-21 17:31
No known issues. You mentioned you set the value to 10, 50, 99, 100.

What value? Do you mean `DefaultRolloutPercentage`?

**Comment by brenda-campbell** [comment] 2024-02-21 19:13
I tried setting it at 50 (did not work), then I tried 99 and then 100.. Then I thought that maybe it was opposite to what I expected so I set to 10. Nothing worked.. 

![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/21212209/7a1bcb7b-bdf2-4207-9e20-b7981f1038b1)

**Comment by rossgrambo** [comment] 2024-02-21 21:11
I'm guessing the code either needs the TargetingFilter added- or needs TargetingContext. If you're on the latest, could you confirm you're using one of these?

Web App:
```csharp
services.AddFeatureManagement()
        .WithTargeting<HttpContextTargetingContextAccessor>();
        
// Then later in code
await fm.IsEnabledAsync(featureName);
```

Console App:
```csharp
await fm.IsEnabledAsync(featureName, targetingContext);
```

**Comment by brenda-campbell** [comment] 2024-02-21 21:57
I'm following the instructions outlined in these pages [https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core?WT.mc_id=Portal-Microsoft_Azure_AzConfig](url)

I've added the code as suggested to the dotnet app that I created (am testing this specifically) so the code is based on the learning page:

// Add Azure App Configuration middleware to the container of services.
builder.Services.AddAzureAppConfiguration();
// Add feature management to the container of services.
builder.Services.AddFeatureManagement();
builder.Services.AddFeatureManagement().AddFeatureFilter<PercentageFilter>();

// Bind configuration "TestApp:Settings" section to the Settings object
builder.Services.Configure<Settings>(builder.Configuration.GetSection("TestApp:Settings"));

Everything works until I add filtering for the Targeting filter (as shown in previous screen shot). 

This is based on released code - creating AppConfiuration is Azure portal, adding Feature flag using Feature manager and then adding filter feature and trying to get it to work in a web app. Works file for the TimeWindow feature filter but not working for the  Targeting feature filter 
![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/21212209/516babc2-8db6-428e-8a19-6af70e625a08)

**Comment by rossgrambo** [comment] 2024-02-22 00:00
Thank you for clarifying. We should update those docs to make it clearer. 

Before v3.0, you used to have to add each filter like:
```csharp
    services.AddFeatureManagement().AddFeatureFilter<PercentageFilter>();
```

But we now add them for you when you call `AddFeatureManagement()` https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/src/Microsoft.FeatureManagement/ServiceCollectionExtensions.cs#L59C13-L65C67

This is likely why your time window filter was working without calling `AddFeatureFilter<TimeWindowFilter>()`

Targeting is a specific case. The library needs "TargetingContext" to know who the user is before they can target off them. This means it needs a way to get it (ITargetingContextAccessor) or it needs to explicitly be given a "TargetingContext" object.

I suggest you update to the latest v3 package and use WithTargeting (example: https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/Startup.cs#L48)
```csharp
    .WithTargeting<HttpContextTargetingContextAccessor>()
```

Without upgrading, you can add the filter and context separately (example: https://github.com/microsoft/FeatureManagement-Dotnet/blob/release/v2/examples/FeatureFlagDemo/Startup.cs#L61)
```csharp
//
// Enable the use of IHttpContextAccessor
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();

//
// Add required services for TargetingFilter
services.AddSingleton<ITargetingContextAccessor, HttpContextTargetingContextAccessor>();

...
        .AddFeatureFilter<TargetingFilter>()
```

Let me know if that helps.

**Comment by brenda-campbell** [comment] 2024-02-22 12:26
Thanks for getting back but I am still not having success in seeing this working. I am using VS Code to create a dotnet app which I am running. When I try any of the suggestions above they don't work. For example:
If I try to add the filter as follows 
builder.Services.AddFeatureManagement().AddFeatureFilter<TargetingFilter>(); 
then the project builds but when I try to run (dotnet run) the following error is reported:

Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.FeatureManagement.IFeatureFilterMetadata Lifetime: Singleton ImplementationType: Microsoft.FeatureManagement.FeatureFilters.TargetingFilter': Unable to resolve service for type 'Microsoft.FeatureManagement.FeatureFilters.ITargetingContextAccessor' while attempting to activate 'Microsoft.FeatureManagement.FeatureFilters.TargetingFilter'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.FeatureManagement.IFeatureFilterMetadata Lifetime: Singleton ImplementationType: Microsoft.FeatureManagement.FeatureFilters.TargetingFilter': Unable to resolve service for type 'Microsoft.FeatureManagement.FeatureFilters.ITargetingContextAccessor' while attempting to activate 'Microsoft.FeatureManagement.FeatureFilters.TargetingFilter'.

If I try to use the suggestion you provided, i.e. 
... TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
then the project won't build due to: 
error CS1061: 'WebApplicationBuilder' does not contain a definition for 'services' and no accessible extension method 'services' accep 
ting a first argument of type 'WebApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

The first suggestion also does not appear to work as just get build errors like:
error CS0122: 'FeatureManagementBuilder' is inaccessible due to its protection level 
error CS0122: 'FeatureManagementBuilder.AddFeatureFilter<T>()' is inaccessible due to its protection level

Is there any sample code where this works as expected for v2 or how do I update to v3 (from within my VS Code editor)? 

Thanks for your help

**Comment by brenda-campbell** [comment] 2024-02-22 12:40
Just wanted to check on the example code  https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/Startup.cs#L48 as I noticed:

using **FeatureFlagDemo.FeatureManagement;**
using **FeatureFlagDemo.FeatureManagement.FeatureFilters;**
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection.Extensions;
using **Microsoft.FeatureManagement**;

Where is the package for FeatureFlagDemo that this example is using?

**Comment by zhiyuanliang-ms** [comment] 2024-02-22 17:43
Hi, @brenda-campbell

This may be unrelated to this issue. But I noticed the screenshot you provided:
![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/141655842/23f67355-6219-433b-b451-d0ebba575c6c)

You should not call AddFeatureManagement() for multiple times.

The correct usage is:
``` c#
builder.Services.AddFeatureManagement()
                         .AddFeatureFilter<MyFilter1>()
                         .AddFeatureFilter<MyFilter2>()
                         .WithTargeting<MyTargetingContextAccessor>();
```

**Comment by zhiyuanliang-ms** [comment] 2024-02-22 17:47
Hi, @brenda-campbell 

> Where is the package for FeatureFlagDemo that this example is using?

The FeatureFlagDemo project refers to the code base of Microsoft.FeatureManagement directly:

https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/FeatureFlagDemo.csproj#L14

**Comment by zhiyuanliang-ms** [comment] 2024-02-22 18:00
Hi, @brenda-campbell 

> Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.FeatureManagement.IFeatureFilterMetadata Lifetime: Singleton ImplementationType: Microsoft.FeatureManagement.FeatureFilters.TargetingFilter': Unable to resolve service for type 'Microsoft.FeatureManagement.FeatureFilters.ITargetingContextAccessor' while attempting to activate 'Microsoft.FeatureManagement.FeatureFilters.TargetingFilter'.)
> ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.FeatureManagement.IFeatureFilterMetadata Lifetime: Singleton ImplementationType: Microsoft.FeatureManagement.FeatureFilters.TargetingFilter': Unable to resolve service for type 'Microsoft.FeatureManagement.FeatureFilters.ITargetingContextAccessor' while attempting to activate 'Microsoft.FeatureManagement.FeatureFilters.TargetingFilter'.

These error messages seem like DI container fails to resolve ITargetingContextAccessor.

> The first suggestion also does not appear to work as just get build errors like:
> error CS0122: 'FeatureManagementBuilder' is inaccessible due to its protection level
> error CS0122: 'FeatureManagementBuilder.AddFeatureFilter()' is inaccessible due to its protection level

May I know how did you get this error? How did you call AddFeatureFilter()?

> Is there any sample code where this works as expected for v2?

Select tag 2.6.1 and you can see the v2 code base and examples for it
<img width="199" alt="image" src="https://github.com/microsoft/FeatureManagement-Dotnet/assets/141655842/6650226e-960c-4c40-a287-6603d2ca9c5d">

**Comment by rossgrambo** [comment] 2024-02-22 19:32
Here's a link to an example in the latest (3.1.1): https://github.com/microsoft/FeatureManagement-Dotnet/blob/release/v3/examples/FeatureFlagDemo/Startup.cs

Here's a link to an example in the latest v2 (2.6.1): https://github.com/microsoft/FeatureManagement-Dotnet/blob/release/v2/examples/FeatureFlagDemo/Startup.cs

> using FeatureFlagDemo.FeatureManagement;
using FeatureFlagDemo.FeatureManagement.FeatureFilters;

Those are custom namespaces the demo project created. You don't need them. 

For V3- I left out the HttpContextAccessor on accident. It should be:
```csharp
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();

services.AddFeatureManagement()
        .WithTargeting<HttpContextTargetingContextAccessor>();
```

> error CS1061: 'WebApplicationBuilder' does not contain a definition for 'services' and no accessible extension method 'services' accepting a first argument of type 'WebApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

If using the builder it should be a capital "S" Services:
```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```

Alternatively- if you are able to provide your Program.cs or your Startup.cs we might be able to suggest the solution directly.

**Comment by brenda-campbell** [comment] 2024-02-22 20:20
Hi @rossgrambo - Thanks for the help. Here is my Program.cs class (I've added package v3.0.0 for FeatureManagement). This code does not compile after adding the 2 lines (in bold)


using TestAppConfig;
using Microsoft.Extensions.Configuration.AzureAppConfiguration;
using Microsoft.FeatureManagement;
using Microsoft.FeatureManagement.FeatureFilters;

var builder = WebApplication.CreateBuilder(args);
// Retrieve the connection string
string connectionString = builder.Configuration.GetConnectionString("AppConfig");
// Load configuration from Azure App Configuration
builder.Configuration.AddAzureAppConfiguration(options =>
    {
        options.Connect(builder.Configuration["ConnectionStrings:AppConfig"])
            // Load all keys that start with `TestApp:` and have no label
            .Select("TestApp:*", LabelFilter.Null)
            // Configure to reload configuration if the registered sentinel key is modified
            .ConfigureRefresh(refreshOptions =>
                refreshOptions.Register("TestApp:Settings:Sentinel", refreshAll: true));
        options.UseFeatureFlags();
    });
// Add services to the container.
builder.Services.AddRazorPages();
// Add Azure App Configuration middleware to the container of services.
builder.Services.AddAzureAppConfiguration();
// Add Feature Management services to the container.
builder.Services.AddFeatureManagement();
**// When I add these 2 lines then I get an error.. 
builder.Services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
builder.Services.AddFeatureManagement()
        .WithTargeting<HttpContextTargetingContextAccessor>();**

// Bind configuration "TestApp:Settings" section to the Settings object
builder.Services.Configure<Settings>(builder.Configuration.GetSection("TestApp:Settings"));
var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}
// Use Azure App Configuration middleware for dynamic configuration refresh.
app.UseAzureAppConfiguration();
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();
app.MapRazorPages();
app.Run();

**Comment by brenda-campbell** [comment] 2024-02-22 20:49
Just to outline what I did in steps in a new project:
Using VS Code (open empty folder)
Open Terminal and typed 
> dotnet new webapp --output TestAppConfig2
> cd .\TestAppConfig2\
> dotnet add package Azure.Identity
> dotnet add package Microsoft.Extensions.Configuration.AzureAppConfiguration
> dotnet add package Microsoft.FeatureManagement
> dotnet add package Microsoft.Azure.AppConfiguration.AspNetCore 

Updated the Program class (as above). 
Adding Settings.cs (based on the pages [https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core?WT.mc_id=Portal-Microsoft_Azure_AzConfig](https://github.com/microsoft/FeatureManagement-Dotnet/issues/url)

Added pages for Beta.cshtml & Beta.cshtml.cs and updated _Layout.cshtml to include:
                        <feature name="Beta">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Beta">Beta</a>
                        </li>
                        </feature> 


Program.cs:

using TestAppConfig2;
using Microsoft.Extensions.Configuration.AzureAppConfiguration;
using Microsoft.FeatureManagement;
**using Microsoft.Extensions.DependencyInjection.Extensions;**


var builder = WebApplication.CreateBuilder(args);

// Retrieve the connection string
string connectionString = builder.Configuration.GetConnectionString("AppConfig");

// Load configuration from Azure App Configuration
builder.Configuration.AddAzureAppConfiguration(options =>
    {
        options.Connect(builder.Configuration["ConnectionStrings:AppConfig"])
            // Load all keys that start with `TestApp:` and have no label
            .Select("TestApp:*", LabelFilter.Null)
            // Configure to reload configuration if the registered sentinel key is modified
            .ConfigureRefresh(refreshOptions =>
                refreshOptions.Register("TestApp:Settings:Sentinel", refreshAll: true));
        options.UseFeatureFlags();
    });

// Add services to the container.
builder.Services.AddRazorPages();

// Add Azure App Configuration middleware to the container of services.
builder.Services.AddAzureAppConfiguration();


// Add Feature Management services to the container.
builder.Services.AddFeatureManagement();
builder.Services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
builder.Services.AddFeatureManagement().WithTargeting<HttpContextTargetingContextAccessor>();

// Bind configuration "TestApp:Settings" section to the Settings object
builder.Services.Configure<Settings>(builder.Configuration.GetSection("TestApp:Settings"));

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

// Use Azure App Configuration middleware for dynamic configuration refresh.
app.UseAzureAppConfiguration();

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();

BUILD ERROR:
error CS0246: The type or namespace name 'HttpContextTargetingContextAccessor' could not be found (are you missing a using direct 
ive or an assembly reference?)

**Comment by rossgrambo** [comment] 2024-02-22 23:44
Okay thank you! This is progress. The last issue is that my previous comment left something out. We don't actually ship `HttpContextTargetingContextAccessor` in FeatureManagement. This is something you'll have to define. 

Our example project defines it like this: https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/HttpContextTargetingContextAccessor.cs

Here's our targeting filter guide which has a different TargetingContextAccessor ( https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-targetingfilter-aspnet-core#update-the-web-application-code-to-use-targetingfilter )

_Why dont we include the HttpContextTargetingContextAccessor?_

It's up to the developer to determine how to supply `TargetingContext` (via a `ITargetingContextAccessor` implementation). This means choosing where `UserId` comes from and how `Groups` are populated. If we added one automatically for ASP.NET, we might be able to get away with assuming `UserId` is `httpContext.User.Identity.Name`, but populating groups is a lot less clear and we haven't yet attempted it.

**Comment by brenda-campbell** [comment] 2024-02-23 11:23
Hi @rossgrambo - Thanks for all the help. I got a little further and it build and runs but the functionality does not appear to work as documented. I set up the TargetingFilter as outlined, registered the user and logged in but the Beta page always appears. I'm going to leave it and try again next week maybe. I had it working correctly for TimeWindow but using the new project that I created, I can't get that to work either. 
This is how I set up the Targeting Filter and have following the instructions in the links provided:
![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/21212209/62b4bcc7-ee61-45e8-b684-266d2e0fe8a0)

**Comment by rossgrambo** [comment] 2024-02-23 17:54
Hey @brenda-campbell ,

Happy to hear! Targeting can be slow to test since it's based on whatever context ITargetingContextAccessor is giving and is "sticky" to user ids. This means if UserA is in the group `contoso.com`, they have a 50% chance to see the feature. However this 50% chance is computed in the exact same way every time. Meaning if a user saw the feature, they will always see the feature. 

For my test projects, I randomize the user id on refresh to help me test different users. Assuming you're using something similar to the example `HttpContextTargetingContextAccessor`, you could adjust it to give you randomized users so you'll see the 50% chance better. I do something like:

```csharp
TargetingContext targetingContext = new TargetingContext
{
    UserId = Random.Shared.Next().ToString(),
    Groups = groups
};
```

Let me know if that helps

**Comment by dalager** [comment] 2024-02-25 08:14
@rossgrambo Ah! That last randomized userid comment made it click for me. I was trying to setup a non-session sticky percentage filter on azure, but came to realize that there is no plain Microsoft.Percentage preconfigured Targeting Filter in 

Azure and you have to create a custom filter like below.
Its rather hard to find this in any kind of documentation. Is it because it is considered bad practice to use non-sticky percentage filters? I guess a lot of users would want the user-sticky rollout pct.

```json
{
	"id": "Over56",
	"description": "56 % will see this. Non sticky",
	"enabled": true,
	"conditions": {
		"client_filters": [
			{
				"name": "Microsoft.Percentage",
				"parameters": {
					"Value": 56
				}
			}
		]
	}
```

**Comment by rossgrambo** [comment] 2024-02-26 22:22
Hey @dalager !

Happy to hear! Yes, you're right. This library offers a Percentage filter, but I believe it was removed from the portal for exactly the reason you're saying. Most people want a "sticky" percentage allocation and it was causing issues for users who weren't expecting a truly random filter. 

Let me know if you have ideas for where the docs/portal could be improved. I see now one of our docs needs to be updated- as it talks about Percentage filter but then shows a guide for Targeting Filter- which is not very clear. https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core?WT.mc_id=Portal-Microsoft_Azure_AzConfig#configure-a-feature-filter-in-azure-app-configuration

But happy to hear suggestions for other places.

**Comment by zhiyuanliang-ms** [comment] 2024-02-27 01:56
> I see now one of our docs needs to be updated- as it talks about Percentage filter but then shows a guide for Targeting Filter- which is not very clear. https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core?WT.mc_id=Portal-Microsoft_Azure_AzConfig#configure-a-feature-filter-in-azure-app-configuration
Good catch! @rossgrambo

I am currently working on update our public docs, I can update this doc. Added to my TODO list.

**Comment by zhiyuanliang-ms** [comment] 2024-03-14 03:28
@brenda-campbell 

This [tutorial](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-targetingfilter-aspnet-core) about how to use targeting filter has been updated. Could you follow it to try targeting filter again? 

I will close this issue. If you have any other questions, feel free to reopen this issue or create a new issue. I apologize for any inconvenience caused by the errors in our documentation.

**Closed by zhiyuanliang-ms** 2024-03-14 03:28 UTC
