### ISSUE TITLE
Feature flag with multiple custom filters

### ISSUE THREAD

**Issue by pawel87** [microsoft/FeatureManagement-Dotnet#257] opened 2023-09-07 07:16 UTC
I am trying to configure feature flag that will depends on more than one custom filter.

It looks like it evaluates feature flag to "true" if ANY of filters match criteria.
How to achieve scenario when all custom filters needs to be "true" in order to evaluate "true" result for entire feature flag?

Example feature flag configuration I have (in Azure portal under Feature manager):

`{
	"id": "MyFeatureFlag",
	"description": "Test flag",
	"enabled": true,
	"conditions": {
		"client_filters": [
			{
				"name": "FilterA",
				"parameters": {
					"dependsOnFeatureFlag": "FeatureFlagB"
				}
			},
			{
				"name": "FilterB",
				"parameters": {
					"operatorType": "IsAnyOf",
					"countries": [ "US ", "GB" ]
				}
			}
		]
	}
}`

**Comment by zhiyuanliang-ms** [comment] 2023-09-07 09:27
You can set the "RequirementType" to be "All".

**Comment by pawel87** [comment] 2023-09-07 09:39
> You can set the "RequirementType" to "All". https://github.com/microsoft/FeatureManagement-Dotnet#requirementtype

This one seems to work when defining feature flag configuration in appsettings file.
Adding RequirementType in Azure Portal does not work. It says this property is not allowed:
![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/6252900/f8673c4b-86a5-43ad-9826-42517fda8b67)

The only way how I am able to make it work is:
1. Define basic feature configuration in appsettings file like below (without any parameters that my filters needs):
 ![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/6252900/8beeec5a-01f9-4b5d-ac20-38ae654eccb6)

2. Define parameters in Azure portal (under Feature Manager) so it is possible to be changed/configured:
![image](https://github.com/microsoft/FeatureManagement-Dotnet/assets/6252900/eb4d2870-5efb-4f44-8282-e8c9e72954aa)


What I would like to achieve is to define everything in Azure Portal, not mixing this responsibility between appsettings and azure portal.

If you believe that having "RequirementType" is possible under feature configuration in Azure Portal please guide me with working example. Thank you!

**Comment by zhiyuanliang-ms** [comment] 2023-09-07 15:35
I understand the issue. Sorry for the confusion caused by the Portal.
I need to double check about the usage of "Advanced edot" with the Portal team.

**Comment by jimmyca15** [comment] 2023-09-07 15:58
@pawel87 what you are expecting to work should work, unfortunately there is a bug in the App Configuration SDK. I am working on getting a proper ETA for you of when this is going to be addressed.

**Comment by jimmyca15** [comment] 2023-11-29 23:08
@pawel87 Setting this up with advanced edit like you have shown should now work as long as you are using at least version 7.0.0 of [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/).

Here is an example of a feature using requirement type as shown in "Advanced Edit"

```
{
	"id": "MyFeatureFlag",
	"description": "",
	"enabled": true,
	"conditions": {
		"client_filters": [
			{
				"name": "Foo",
				"parameters": {}
			},
			{
				"name": "Bar",
				"parameters": {}
			}
		]
	}
}
```

We are in the process of rolling out the accompanied UI switch so that advanced edit is not needed to switch between requirement types (All, Any).

**Comment by steven-rothwell** [comment] 2024-01-02 20:25
I added `"requirement_type": "All",` via Advanced Edit so that it looks like this:

```
{
	"id": "my-feature-flag",
	"description": "description of my feature.",
	"enabled": true,
	"conditions": {
		"requirement_type": "All",
		"client_filters": [
			{
				"name": "CustomFilter1",
				"parameters": {
					// My custom parameters are defined in here.
				}
			},
			{
				"name": "CustomFilter2",
				"parameters": {
					// My custom parameters are defined in here.
				}
			}
		]
	}
}
```
But, it is still acting as if it is `Any` instead of `All`.

I do not define the custom filters in the consuming application via appsettings as the consuming apps do not need to know about the custom filters.  I am not using [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/).  Is there a way to have it work with `All` without having each application install this NuGet package and define every custom filter that we have?

**Comment by jimmyca15** [comment] 2024-01-02 21:01
@steven-rothwell are you using [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/) 7.0.0?

**Comment by jimmyca15** [comment] 2024-01-02 21:04
@steven-rothwell if you are not using [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/), how are you getting feature flags into your application?

**Comment by jimmyca15** [comment] 2024-01-03 16:13
@steven-rothwell No worries. Glad to hear that everything is working now !

I will close the issue.

**Closed by jimmyca15** 2024-01-03 16:13 UTC
Labels: question
